# =============================================================================
# mongo-secret.yml
# Menyimpan kredensial root MongoDB secara ter-encode base64.
# Nilai: MONGO_ROOT_USERNAME=admin, MONGO_ROOT_PASSWORD=supersecretpassword
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret          # nama Secret, dirujuk oleh StatefulSet & Deployment backend
type: Opaque                  # tipe generic key-value
data:
  # 'admin' dalam base64
  MONGO_ROOT_USERNAME: YWRtaW4=
  # 'supersecretpassword' dalam base64
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
